/************************************************************************
 * Class Name: BGROutputWrapper
 * This class is wrapper of BGR Output
 * This class contains on BGR output details
 * Author: Susheel(Dec-2019)
************************************************************************/
public class BGROutputWrapper {
    public string operationNumber;
    public string standardOperationId;
    public string outsideOperationItem;
    public Decimal guidelineSequence;
    public string guidelineDescription;
    public string guidelineText;
    public string guidelineType;
    public Boolean signOffRequired;
    public Boolean inspectionSignOffRequired;    
}