/*Wrapper class used for BGMStructure */
public class HLDRStructureWrapper {
    //public string HolderStructureType {set;get;}
    public string ComponentPart {set;get;}
    public string ROP {set;get;}
    public string Qty {set;get;}
    public string ScrapFactor {set;get;}
    public string ComponentScrap {set;get;}
    public String MCKBLD{get;set;}
    public string structureType{get;set;}
    public string leadTime {get;set;}
    //public string LineItemNo {set;get;}
}